/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPublicarRouteImport } from './routes/_authenticated/publicar'
import { Route as JogadorUsernameRouteImport } from './routes/jogador.$username'
import { Route as TimeTeamIdRouteImport } from './routes/time.$teamId'
import { Route as AuthenticatedPartidaNovaRouteImport } from './routes/_authenticated/partida.nova'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublicarRoute = AuthenticatedPublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const JogadorUsernameRoute = JogadorUsernameRouteImport.update({
  id: '/jogador/$username',
  path: '/jogador/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeTeamIdRoute = TimeTeamIdRouteImport.update({
  id: '/time/$teamId',
  path: '/time/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPartidaNovaRoute =
  AuthenticatedPartidaNovaRouteImport.update({
    id: '/partida/nova',
    path: '/partida/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/publicar': typeof AuthenticatedPublicarRoute
  '/jogador/$username': typeof JogadorUsernameRoute
  '/time/$teamId': typeof TimeTeamIdRoute
  '/partida/nova': typeof AuthenticatedPartidaNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/publicar': typeof AuthenticatedPublicarRoute
  '/jogador/$username': typeof JogadorUsernameRoute
  '/time/$teamId': typeof TimeTeamIdRoute
  '/partida/nova': typeof AuthenticatedPartidaNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/publicar': typeof AuthenticatedPublicarRoute
  '/jogador/$username': typeof JogadorUsernameRoute
  '/time/$teamId': typeof TimeTeamIdRoute
  '/_authenticated/partida/nova': typeof AuthenticatedPartidaNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buscar'
    | '/sitemap.xml'
    | '/notificacoes'
    | '/perfil'
    | '/publicar'
    | '/jogador/$username'
    | '/time/$teamId'
    | '/partida/nova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/buscar'
    | '/sitemap.xml'
    | '/notificacoes'
    | '/perfil'
    | '/publicar'
    | '/jogador/$username'
    | '/time/$teamId'
    | '/partida/nova'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/buscar'
    | '/sitemap.xml'
    | '/_authenticated/notificacoes'
    | '/_authenticated/perfil'
    | '/_authenticated/publicar'
    | '/jogador/$username'
    | '/time/$teamId'
    | '/_authenticated/partida/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BuscarRoute: typeof BuscarRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  JogadorUsernameRoute: typeof JogadorUsernameRoute
  TimeTeamIdRoute: typeof TimeTeamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/publicar': {
      id: '/_authenticated/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof AuthenticatedPublicarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/jogador/$username': {
      id: '/jogador/$username'
      path: '/jogador/$username'
      fullPath: '/jogador/$username'
      preLoaderRoute: typeof JogadorUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time/$teamId': {
      id: '/time/$teamId'
      path: '/time/$teamId'
      fullPath: '/time/$teamId'
      preLoaderRoute: typeof TimeTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/partida/nova': {
      id: '/_authenticated/partida/nova'
      path: '/partida/nova'
      fullPath: '/partida/nova'
      preLoaderRoute: typeof AuthenticatedPartidaNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPublicarRoute: typeof AuthenticatedPublicarRoute
  AuthenticatedPartidaNovaRoute: typeof AuthenticatedPartidaNovaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPublicarRoute: AuthenticatedPublicarRoute,
  AuthenticatedPartidaNovaRoute: AuthenticatedPartidaNovaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BuscarRoute: BuscarRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  JogadorUsernameRoute: JogadorUsernameRoute,
  TimeTeamIdRoute: TimeTeamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
